baseURL: "https://FlorianRaichle.github.io"
languageCode: "en-us"
title: "Florian Raichle"
theme: "hugo-profile"
relativeURLs: true

# googleanalytics: UA-xxxxxx-x
show_cv: false
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1
    
params:
  version: 3
  customCSS: false

  favicon: "/logo/new_logo_white52px.png"
  logo_light: "/logo/new_logo_white52px.png"
  logo_dark: "/logo/new_logo_black52px.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  projectTypes: ["project", "thesis"]

  # home
  disable_home: false
  # profile_image: "/images/profile.png"
  name: "Florian Raichle"
  namecolor: ffc107
  profession: "Chemical Engineer"
  github: "https://github.com/florianraichle"
  # gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/florian-raichle-209991200/"
  # twitter: "https://twitter.com/"
  # instagram: "https://instagram.com/florianraichle"
  # facebook: "https://facebook.com"

  # Custom social links
  # customSocialLinks:
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"

  sections:
    - name: home
    - name: about
      description: "Hi, I'm a chemical engineer working at cloudfluid as a developer and CFD engineer.
      The focus of my work so far has been computational fluid dynamics but I'm always trying to learn something new."
      skills: 
      - name: CFD
      - name: Python
      - name: C++
      - name: LaTeX
    - name: experience
    - name: education
    - name: projects
    - name: contact

  # Contact
  disable_contact: false
  contact_content: Whether you have a question or just want to say hello,
  email: "raichle.florian@gmail.com"
  getintouch: Send me a message
