baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Florian Raichle"
theme: "hugo-profile"
relativeURLs: true

# googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1
    
params:
  version: 3
  customCSS: false

  favicon: "/logo/new_logo_white52px.png"
  logo_light: "/logo/new_logo_white52px.png"
  logo_dark: "/logo/new_logo_black52px.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  projectTypes: ["project", "thesis"]

  # home
  disable_home: false
  # profile_image: "/images/profile.png"
  name: "Florian Raichle"
  namecolor: ffc107
  profession: "Chemical Engineer"
  github: "https://github.com"
  gitlab: "https://gitlab.com"
  linkedin: "https://linkedin.com"
  twitter: "https://twitter.com/"
  instagram: "https://instagram.com/"
  facebook: "https://facebook.com"

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fa fa-envelope"
      url: "https://gmail.com"

  sections:
    - name: home
    - name: about
      description: "Hi, I'm Florian Raichle, a chemical engineer who likes to do some creative stuff on the side.
      <br><br>
      
      You can find my works [here](#projects)."
      skills: 
      - name: CFD
      - name: C++
      - name: Python
      - name: LaTeX
    - name: experience
    - name: education
    - name: projects
    - name: contact
  
  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"